using InSpectra.Gen.Tests.TestSupport;

namespace InSpectra.Gen.Tests;

public sealed class RepositoryCodeFilePolicyTests
{
    [Fact]
    public void Source_And_Test_Code_Files_Stay_Within_The_Practical_Line_Limit()
        => AssertNoViolations(
            maximumLines: 300,
            "Non-generated C# files under `src` and `tests` should stay below the repo's practical 300-line target.");

    [Fact]
    public void Source_And_Test_Code_Files_Stay_Within_The_Hard_Line_Limit()
        => AssertNoViolations(
            maximumLines: 500,
            "Non-generated C# files under `src` and `tests` must stay within the hard 500-line limit.");

    private static void AssertNoViolations(int maximumLines, string message)
    {
        var trackedFiles = EnumerateTrackedCodeFiles().ToArray();
        Assert.True(
            trackedFiles.Length > 0,
            "Expected to scan at least one tracked non-generated C# file under 'src' or 'tests', but found none.");

        var violations = trackedFiles
            .Select(path => new CodeFileLength(
                RelativePath: Path.GetRelativePath(FixturePaths.RepoRoot, path).Replace('\\', '/'),
                LineCount: File.ReadLines(path).Count()))
            .Where(file => file.LineCount > maximumLines)
            .OrderByDescending(file => file.LineCount)
            .ThenBy(file => file.RelativePath, StringComparer.Ordinal)
            .ToArray();

        Assert.True(
            violations.Length == 0,
            violations.Length == 0
                ? null
                : $"{message}{Environment.NewLine}{string.Join(Environment.NewLine, violations.Select(static file => $"- {file.RelativePath} ({file.LineCount} lines)"))}");
    }

    private static IEnumerable<string> EnumerateTrackedCodeFiles()
    {
        foreach (var root in new[] { "src", "tests" })
        {
            var rootPath = Path.Combine(FixturePaths.RepoRoot, root);
            foreach (var path in Directory.EnumerateFiles(rootPath, "*.cs", SearchOption.AllDirectories))
            {
                if (IsIgnoredPath(path) || IsGeneratedFile(path))
                {
                    continue;
                }

                yield return path;
            }
        }
    }

    private static bool IsIgnoredPath(string path)
    {
        var segments = path.Split(Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar);
        return segments.Any(segment =>
            string.Equals(segment, "bin", StringComparison.OrdinalIgnoreCase)
            || string.Equals(segment, "obj", StringComparison.OrdinalIgnoreCase));
    }

    private static bool IsGeneratedFile(string path)
    {
        var fileName = Path.GetFileName(path);
        if (fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        foreach (var line in File.ReadLines(path).Take(5))
        {
            if (line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private sealed record CodeFileLength(string RelativePath, int LineCount);
}
