import { ArrowRight, BookOpen, Copy, Check, ExternalLink } from "lucide-react";
import { GitHubIcon } from "./GitHubIcon";
import { useState } from "react";

export function AboutPage() {
  const [copied, setCopied] = useState(false);

  function handleCopy() {
    navigator.clipboard.writeText("dotnet tool install -g InSpectra.Gen").then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  const [activeTab, setActiveTab] = useState<"file" | "exec" | "output">("file");

  return (
    <main className="about-page">
      {/* Hero */}
      <section className="about-hero">
        <div className="about-badge">
          <span className="dot" />
          Built on the OpenCLI specification
        </div>
        <h1>
          Turn any CLI into<br />
          <span className="accent">beautiful docs</span>
        </h1>
        <p className="about-hero-sub">
          Generate polished, interactive documentation from your CLI's OpenCLI spec.
          Markdown or relocatable HTML app bundles. One command.
        </p>

        <div className="about-install">
          <span className="prompt">$</span>
          <span className="cmd">dotnet tool install</span>
          <span className="pkg">-g InSpectra.Gen</span>
          <button
            type="button"
            className={`about-copy-btn${copied ? " copied" : ""}`}
            onClick={handleCopy}
          >
            {copied ? <Check aria-hidden="true" /> : <Copy aria-hidden="true" />}
            <span>{copied ? "Copied!" : "Copy"}</span>
          </button>
        </div>

        <div className="about-terminal-wrap">
          <div className="about-terminal-bar">
            <span className="dot-r" /><span className="dot-y" /><span className="dot-g" />
            <span className="title">inspectra</span>
            <span />
          </div>
          <div className="about-terminal">
            <div className="line"><span className="p">$</span> <span className="c">inspectra</span> <span className="a">render file html</span> <span>jellyfin.json</span> <span className="f">--xmldoc</span> <span>jellyfin.xml</span></div>
            <div className="line"><span className="dim">&nbsp;&nbsp;Validating OpenCLI schema...</span> <span className="ok">OK</span></div>
            <div className="line"><span className="dim">&nbsp;&nbsp;Normalizing 47 commands, 128 options...</span> <span className="ok">OK</span></div>
            <div className="line"><span className="dim">&nbsp;&nbsp;Enriching from XML metadata...</span> <span className="ok">OK</span></div>
            <div className="line"><span className="dim">&nbsp;&nbsp;Copying HTML app bundle...</span> <span className="ok">OK</span></div>
            <div className="line"><span className="ok">&nbsp;&nbsp;&#10003; Written index.html and assets to jellyfin-docs/</span> <span className="dim">(relocatable static bundle)</span></div>
          </div>
        </div>
      </section>

      {/* Examples */}
      <section className="about-section">
        <div className="about-section-label">Live Examples</div>
        <div className="about-section-title">See it in action</div>
        <p className="about-section-desc">
          Real documentation generated by InSpectraGen. Click through to explore the full interactive HTML output.
        </p>

        <div className="about-examples">
          <a href="#/pkg/InSpectra.Gen" className="about-example-card about-example-self">
            <div className="card-title">InSpectraGen</div>
            <div className="card-alias">inspectra</div>
            <div className="card-desc">
              The tool documents itself. This is the full reference generated from its own OpenCLI spec.
            </div>
            <span className="card-link">
              View live docs <ArrowRight aria-hidden="true" size={14} />
            </span>
          </a>

          <a href="./examples/jellyfin-cli/" className="about-example-card">
            <div className="card-title">Jellyfin CLI</div>
            <div className="card-alias">jf</div>
            <div className="card-desc">
              Manage your Jellyfin media server from the command line. Auth, libraries, users, playlists, and more.
            </div>
            <span className="card-link">
              View live docs <ArrowRight aria-hidden="true" size={14} />
            </span>
          </a>

          <a href="./examples/jdownloader-remotecli/" className="about-example-card">
            <div className="card-title">JDownloader RemoteCli</div>
            <div className="card-alias">jdr</div>
            <div className="card-desc">
              Remote-control your JDownloader instance from the terminal. Devices, downloads, accounts, and events.
            </div>
            <span className="card-link">
              View live docs <ArrowRight aria-hidden="true" size={14} />
            </span>
          </a>

          <a href="#/" className="about-example-card">
            <div className="card-title">Browse All Packages</div>
            <div className="card-alias">NuGet browser</div>
            <div className="card-desc">
              Explore indexed .NET CLI tool packages and inspect their command structure directly.
            </div>
            <span className="card-link">
              Open browser <ArrowRight aria-hidden="true" size={14} />
            </span>
          </a>
        </div>
      </section>

      {/* Features */}
      <section className="about-section">
        <div className="about-section-label">Features</div>
        <div className="about-section-title">Everything you need</div>
        <p className="about-section-desc">
          From schema validation to interactive viewers, InSpectraGen handles the full pipeline.
        </p>

        <div className="about-features">
          <div className="about-feature">
            <span className="about-feature-icon">&#9997;</span>
            <div className="about-feature-name">Markdown & HTML</div>
            <div className="about-feature-desc">Two output formats. GitHub-compatible Markdown for repos, plus an HTML app bundle for static hosting.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#9889;</span>
            <div className="about-feature-name">Interactive SPA</div>
            <div className="about-feature-desc">Generated HTML is a full single-page app with hash-based deep links, command filtering, and static-host friendly routing.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#9681;</span>
            <div className="about-feature-name">Drop or Link</div>
            <div className="about-feature-desc">Boot with injected data, fetchable URLs, or manual file import. One viewer covers local previews and hosted bundles.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#9000;</span>
            <div className="about-feature-name">Source of Truth</div>
            <div className="about-feature-desc">HTML runs on raw <code>opencli.json</code> plus optional <code>xmldoc.xml</code>. No parallel viewer schema.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#9776;</span>
            <div className="about-feature-name">Markdown Layouts</div>
            <div className="about-feature-desc">Markdown supports single-file and tree layouts. HTML ships as an app bundle directory.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#10003;</span>
            <div className="about-feature-name">Schema Validation</div>
            <div className="about-feature-desc">Validates input against an embedded JSON Schema (2020-12) with detailed error messages.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#10010;</span>
            <div className="about-feature-name">XML Enrichment</div>
            <div className="about-feature-desc">Optionally merge richer descriptions from XML metadata. Additive only, never overwrites.</div>
          </div>
          <div className="about-feature">
            <span className="about-feature-icon">&#9211;</span>
            <div className="about-feature-name">Zero Network Calls</div>
            <div className="about-feature-desc">Fully offline. No telemetry, no CDN, no external requests. Runs locally, writes to disk.</div>
          </div>
        </div>
      </section>

      {/* Quick Start */}
      <section className="about-section">
        <div className="about-section-label">Quick Start</div>
        <div className="about-section-title">Three steps to docs</div>
        <p className="about-section-desc">
          Install the tool, point it at your CLI, and open the result.
        </p>

        <div className="about-quickstart">
          <div className="about-qs-steps">
            <div className="about-qs-step">
              <div className="about-qs-num">1</div>
              <div className="about-qs-text"><strong>Install the tool</strong><br />Available as a .NET global tool via NuGet. Requires .NET 10 SDK.</div>
            </div>
            <div className="about-qs-step">
              <div className="about-qs-num">2</div>
              <div className="about-qs-text"><strong>Render from a file</strong><br />Pass your <code>opencli.json</code> and optional <code>xmldoc.xml</code>. Pick Markdown or HTML.</div>
            </div>
            <div className="about-qs-step">
              <div className="about-qs-num">3</div>
              <div className="about-qs-text"><strong>Or render from a live CLI</strong><br />Use <code>exec</code> mode to invoke a CLI directly and capture its OpenCLI output.</div>
            </div>
          </div>

          <div className="about-qs-code">
            <div className="about-qs-tabs">
              <button type="button" className={`about-qs-tab${activeTab === "file" ? " active" : ""}`} onClick={() => setActiveTab("file")}>From File</button>
              <button type="button" className={`about-qs-tab${activeTab === "exec" ? " active" : ""}`} onClick={() => setActiveTab("exec")}>From CLI</button>
              <button type="button" className={`about-qs-tab${activeTab === "output" ? " active" : ""}`} onClick={() => setActiveTab("output")}>Output Modes</button>
            </div>
            <div className={`about-qs-panel${activeTab === "file" ? " active" : ""}`}>
              <span className="comment"># Install</span>{"\n"}
              <span className="c">dotnet tool install</span> -g InSpectra.Gen{"\n"}
              {"\n"}
              <span className="comment"># Render interactive HTML</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render file html</span> \{"\n"}
              {"  "}mycli.json <span className="f">--xmldoc</span> mycli.xml \{"\n"}
              {"  "}<span className="f">--out-dir</span> ./docs{"\n"}
              {"\n"}
              <span className="comment"># Render Markdown</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render file markdown</span> \{"\n"}
              {"  "}mycli.json <span className="f">--out</span> docs.md
            </div>
            <div className={`about-qs-panel${activeTab === "exec" ? " active" : ""}`}>
              <span className="comment"># Render directly from a running CLI</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render exec html</span> \{"\n"}
              {"  "}jf <span className="f">--with-xmldoc</span> \{"\n"}
              {"  "}<span className="f">--out-dir</span> ./jellyfin-docs{"\n"}
              {"\n"}
              <span className="comment"># Custom OpenCLI arguments</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render exec markdown</span> \{"\n"}
              {"  "}mytool <span className="f">--opencli-arg</span> "cli opencli" \{"\n"}
              {"  "}<span className="f">--out</span> docs.md
            </div>
            <div className={`about-qs-panel${activeTab === "output" ? " active" : ""}`}>
              <span className="comment"># HTML always writes an app bundle directory</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render file html</span> \{"\n"}
              {"  "}mycli.json \{"\n"}
              {"  "}<span className="f">--out-dir</span> ./docs/{"\n"}
              {"\n"}
              <span className="comment"># Markdown keeps tree layout support</span>{"\n"}
              <span className="c">inspectra</span> <span className="a">render file markdown</span> \{"\n"}
              {"  "}mycli.json \{"\n"}
              {"  "}<span className="f">--layout</span> tree \{"\n"}
              {"  "}<span className="f">--out-dir</span> ./docs/
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="about-footer">
        <div>
          Built on the <a href="https://opencli.org/" target="_blank" rel="noopener noreferrer">OpenCLI specification</a>
        </div>
        <div className="about-footer-links">
          <a href="https://github.com/JKamsker/InSpectra" target="_blank" rel="noopener noreferrer">
            <GitHubIcon aria-hidden="true" size={14} />
            GitHub
          </a>
          <a href="https://opencli.org/" target="_blank" rel="noopener noreferrer">
            <ExternalLink aria-hidden="true" size={14} />
            OpenCLI Spec
          </a>
          <a href="https://github.com/spectreconsole/open-cli" target="_blank" rel="noopener noreferrer">
            <BookOpen aria-hidden="true" size={14} />
            Spec Repo
          </a>
        </div>
      </footer>
    </main>
  );
}
