namespace InSpectra.Gen.Acquisition.Promotion.Services;

using InSpectra.Gen.Acquisition.App.Machine;

using InSpectra.Gen.Acquisition.Infrastructure.Host;

using InSpectra.Gen.Acquisition.Infrastructure.Paths;

using InSpectra.Gen.Acquisition.Infrastructure.Json;

using System.Text;
using System.Text.Json.Nodes;

internal sealed class PromotionCommandService
{
    public async Task<int> WriteNotesAsync(
        string summaryPath,
        string workflowRunUrl,
        string bodyOutputPath,
        string? commentIndexPath,
        bool json,
        CancellationToken cancellationToken)
    {
        var summary = await JsonNodeFileLoader.TryLoadJsonObjectAsync(summaryPath, cancellationToken)
            ?? throw new InvalidOperationException($"Summary file '{summaryPath}' is empty.");
        var commentLookup = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

        if (!string.IsNullOrWhiteSpace(commentIndexPath) && File.Exists(commentIndexPath))
        {
            var comments = await JsonNodeFileLoader.TryLoadJsonArrayAsync(commentIndexPath, cancellationToken) ?? [];
            foreach (var entryNode in comments)
            {
                if (entryNode is not JsonObject entry)
                {
                    continue;
                }

                var packageId = entry["packageId"]?.GetValue<string>();
                var version = entry["version"]?.GetValue<string>();
                var commentUrl = entry["commentUrl"]?.GetValue<string>();
                if (!string.IsNullOrWhiteSpace(packageId) && !string.IsNullOrWhiteSpace(version) && !string.IsNullOrWhiteSpace(commentUrl))
                {
                    commentLookup[$"{packageId}|{version}"] = commentUrl;
                }
            }
        }

        var builder = new StringBuilder();
        builder.AppendLine($"Promote the completed untrusted analysis batch `{summary["batchId"]?.GetValue<string>()}`.");
        builder.AppendLine();
        builder.AppendLine("Source workflow run:");
        builder.AppendLine($"- `{workflowRunUrl}`");
        builder.AppendLine();
        builder.AppendLine("Result summary:");
        builder.AppendLine($"- Success: `{summary["successCount"]?.GetValue<int?>() ?? 0}`");
        builder.AppendLine($"- Terminal negative: `{summary["terminalNegativeCount"]?.GetValue<int?>() ?? 0}`");
        builder.AppendLine($"- Retryable failure: `{summary["retryableFailureCount"]?.GetValue<int?>() ?? 0}`");
        builder.AppendLine($"- Terminal failure: `{summary["terminalFailureCount"]?.GetValue<int?>() ?? 0}`");
        builder.AppendLine($"- Missing artifacts: `{summary["missingCount"]?.GetValue<int?>() ?? 0}`");
        builder.AppendLine();

        AppendPackageSection(builder, "Successful packages:", summary["successItems"] as JsonArray, FormatSuccessItem);

        builder.AppendLine("Non-success details:");
        var nonSuccessItems = summary["nonSuccessItems"] as JsonArray ?? [];
        if (nonSuccessItems.Count == 0)
        {
            builder.AppendLine("- None.");
        }
        else
        {
            foreach (var itemNode in nonSuccessItems)
            {
                if (itemNode is not JsonObject item)
                {
                    continue;
                }

                var packageId = item["packageId"]?.GetValue<string>() ?? string.Empty;
                var version = item["version"]?.GetValue<string>() ?? string.Empty;
                var status = item["status"]?.GetValue<string>() ?? string.Empty;
                var classification = item["classification"]?.GetValue<string>() ?? string.Empty;
                var key = $"{packageId}|{version}";
                var label = commentLookup.TryGetValue(key, out var commentUrl)
                    ? $"[{packageId} {version}]({commentUrl})"
                    : $"{packageId} {version}";
                builder.AppendLine($"- {label}: {status}, {classification}");
            }
        }

        builder.AppendLine();
        builder.AppendLine("Generated by `Promote Untrusted Analysis Results`.");

        RepositoryPathResolver.WriteTextFile(bodyOutputPath, builder.ToString());
        var result = new { bodyOutputPath = Path.GetFullPath(bodyOutputPath) };
        var output = Runtime.CreateOutput();
        return await output.WriteSuccessAsync(
            result,
            [
                new SummaryRow("Body output", Path.GetFullPath(bodyOutputPath)),
            ],
            json,
            cancellationToken);
    }

    private static void AppendPackageSection(
        StringBuilder builder,
        string title,
        JsonArray? items,
        Func<JsonObject, string> formatter)
    {
        if (items is null || items.Count == 0)
        {
            return;
        }

        builder.AppendLine(title);
        foreach (var item in items.OfType<JsonObject>())
        {
            builder.AppendLine(formatter(item));
        }

        builder.AppendLine();
    }

    private static string FormatSuccessItem(JsonObject item)
    {
        var packageId = item["packageId"]?.GetValue<string>() ?? string.Empty;
        var version = item["version"]?.GetValue<string>() ?? string.Empty;
        var previousVersion = item["previousVersion"]?.GetValue<string>();
        return item["change"]?.GetValue<string>() switch
        {
            "created" => $"- {packageId} `{version}` (created)",
            "updated" => $"- {packageId} `{(string.IsNullOrWhiteSpace(previousVersion) ? "?" : previousVersion)}` -> `{version}` (updated)",
            _ => $"- {packageId} `{version}` (unchanged indexed output)",
        };
    }
}
